EvalWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from Eval.views import (
    HomePageListView, AuthorEvaluationsListView, EvaluationListView,
    create_index, create_eval
)


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomePageListView.as_view(), name='home-page'),
    path('author/<str:name>/', AuthorEvaluationsListView.as_view(), name='author-posts'),
    path('eval-post/<int:pk>/', EvaluationListView.as_view(), name='eval-detail'),
    path('create-index/', create_index, name = 'create-index'),
    path('create-eval/',create_eval, name = 'create-eval'),
    
    # USER VIEWS
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),

    # AUTH VIEWS 
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

]

Eval/models.py
from django.db import models
from django.contrib.auth.models import User

class Author(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Evaluation(models.Model):
    eval_author = models.ForeignKey(Author, on_delete=models.CASCADE)
    eval_name = models.CharField(max_length=100)
    date_created = models.DateTimeField ("Eval Date Created")

    def __str__(self):
        return f"{self.eval_author} - {self.eval_name} - {self.date_created}"
    
class Question(models.Model):
    eval_form = models.ForeignKey(Evaluation, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.eval_form} - {self.question_text}"

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    answers = models.IntegerField(default=0)
    
    def __str__(self):
        return f"{self.question} - {self.choice_text} - {self.answers}"

class Answer(models.Model):
    evaluation = models.ForeignKey(Evaluation, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    selected_choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    

users/models.py
from django.db import models

# Create your models here.

Eval/forms.py
from django import forms
from . models import (
    Evaluation,Answer
)
from .models import Evaluation, Question, Choice

class EvaluationForm(forms.ModelForm):
    class Meta:
        model = Evaluation
        fields = ['eval_name', 'date_created']
        widgets = {
            'eval_name': forms.TextInput(attrs={'class': 'form-control', 'style':'width: 300px;'}),
            'date_created': forms.TextInput(attrs={'class': 'form-control', 'type': 'date', 'style':'width: 300px;'}),
        }

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']
        widgets = {
            'question_text':forms.TextInput(attrs={'class':'form-control', 'style':'width: 300px;'}),
        }

class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']
        widgets = {
            'choice_text':forms.TextInput(attrs={'class':'form-control', 'style':'width: 300px;'}),
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['question', 'selected_choice']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# THIS FILE IS CUSTOMIZED UserCreationForm
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

Eval/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .forms import EvaluationForm,QuestionForm,ChoiceForm
from .models import Author, Evaluation, Question, Choice, Answer

from django.views.generic import ListView

from . models import (
    Author,Evaluation,Question,Choice
)


@method_decorator(login_required, name='dispatch')
class HomePageListView(ListView):
    model = Evaluation
    template_name = 'home.html'
    context_object_name = 'evaluations'
    # paginated_by = 5

@method_decorator(login_required, name='dispatch')
class AuthorEvaluationsListView(ListView):
    model = Evaluation
    template_name = 'partials/author_eval.html'
    context_object_name = 'evaluations'

    def get_queryset(self):
        name = self.kwargs.get('name')
        author = get_object_or_404(Author, name=name)
        return Evaluation.objects.filter(eval_author=author).order_by('-date_created')

@method_decorator(login_required, name='dispatch')
class EvaluationListView(ListView):
    model = Evaluation
    template_name = "partials/answer_eval.html"  
    context_object_name = 'evaluations'


def create_index(request):
    context = {
        'evalForm':EvaluationForm(),
        'questionForm': QuestionForm(),

    }    
    return render(request, 'create_index.html',context)

def create_eval(request):
    if request.method == 'POST':
        pass

    context = {
        'questionForm':QuestionForm(),
        'choiceForm':ChoiceForm()
    }

    return render(request, 'partials/form_eval.html',context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from . forms import UserRegisterForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST) # SEE forms.py
        if form.is_valid():
            form.save() 
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account has been created! You are now able to log in.') # FLASH MESSAGE
            return redirect('login')

    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form':form})

@login_required
def profile(request):
    return render(request, 'users/profile.html')

Eval/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://unpkg.com/htmx.org@1.9.8"></script>
    <link rel="stylesheet" type = "text/css" href="{% static 'main.css' %}">
    
    {% if title %}
        <title>Evaluation Web  - {{title}}</title>
    {% else %}
        <title>Evaluation Web </title>
    {% endif %}

</head> 

<body hx-headers='{"X-CSRFToken": "{{ csrf_token}}"}'>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'home-page' %}">Eval Web App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'home-page' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'create-index' %}">Create Form</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </main>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>

Eval/templates/create_index.html
{% extends 'base.html' %}

{% block content %}

<h2>Create Evaluation</h2>
    <div class="row">
        <div class="col-12 col-md-6">
            <div class="form-group">
                <label for="{{ evalForm.eval_name.id_for_label }}">{{ evalForm.eval_name.label }}</label>
                {{ evalForm.eval_name }}
            </div>
        </div>

        <div class="col-12 col-md-6">
            <div class="form-group">
                <label for="{{ evalForm.date_created.id_for_label }}">{{ evalForm.date_created.label }}</label>
                {{ evalForm.date_created }}
            </div>
        </div>
    </div>

    <div id="form-eval">
        {% include 'partials/form_eval.html' %}
    </div>

    <div class="my-4">
        <button type="button" class="btn btn-success me-2"
        hx-get="{% url 'create-eval' %}"
        hx-target="#form-eval"
        hx-swap="beforeend"> + Add Questions </button.>
    </div>





{% endblock %}

Eval/templates/home.html
{% extends 'base.html' %}
{% block content %}

{% for eval in evaluations %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'author-posts' eval.eval_author.name %}">{{ eval.eval_author }}</a>
            <small class="text-muted">{{ eval.date_created|date:"F d, Y" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'eval-detail' eval.id%}">
            {{ eval.eval_name }}</a></h2>
    </div>
</article>

{% endfor %}


{% endblock content %}

Eval/templates/partials/answer_eval.html
<!-- evaluation_list.html -->
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <ul>
      {% for evaluation in object_list %}
        <h2>{{ evaluation.eval_name }}</h2>
        <form method="post" action="{% url 'answer-eval' evaluation.pk %}">
          {% csrf_token %}
          
          {% for question in evaluation.question_set.all %}
            <li>
              <h3>{{ question.question_text }}</h3>
              
              {% for choice in question.choice_set.all %}
                <label>
                  <input type="radio" name="selected_choice" value="{{ choice.id }}" required>
                  {{ choice.choice_text }}
                </label>
              {% endfor %}
            </li>
          {% endfor %}
            <button type="submit" class="btn btn-primary">Submit Answers</button>
        </form>
      {% endfor %}
    </ul>
  </div>
{% endblock content %}

Eval/templates/partials/author_eval.html
{% extends 'base.html' %}

{% block content %}


{% for eval in evaluations %}
    <h1>Evaluation Forms Created By {{eval.eval_author}}</h1>   
    <h2>{{ eval.eval_name }}</h2>
    <p>Author: {{ eval.eval_author.name }}</p>
    <p>Date Created: {{ eval.date_created }}</p>

    <h3>Questions and Choices: </h3>

    {% for question in eval.question_set.all %}
        <ul>
            <li>{{ question.question_text }}</li>

            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }}</li>
            {% endfor %}
        </ul>
    {% endfor %}

{% endfor %}

{% endblock content %}

Eval/templates/partials/evaltest.html
<h1>{{ evaluation.eval_name}}</h1>

Eval/templates/partials/form_eval.html
<form>
    <div class="row">
        <div class="col-md-6 mt-3">
                <div class="form-group">
                <label for="{{ questionForm.question_text.id_for_label }}">{{ questionForm.question_text.label }}</label>
                {{ questionForm.question_text }}
            </div>
        </div>

        <div class="col-md-6 mt-3">
            <div class="form-group">
                <label for="{{ choiceForm.choice_text.id_for_label }}">{{ choiceForm.choice_text.label }}</label>
                {{ choiceForm.choice_text }}
            </div>
        </div>







<!--
    <div class="col-md-6 align-self-end">
        <div class="text-md-right">
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
    </div>
-->
    </div>
</form>

Eval/templates/partials/submit_eval.html
<h1> You Submitted Successfully</h1>

templates/home.html
{% extends 'base.html' %}
{% block content %}

{% for eval in evaluations %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'author-posts' eval.eval_author.name %}">{{ eval.eval_author }}</a>
            <small class="text-muted">{{ eval.date_created|date:"F d, Y" }}</small>
        </div>
        <h2><a class="article-title" href="#">
            {{ eval.eval_name }}</a></h2>
    </div>
</article>

{% endfor %}


{% endblock content %}

templates/partials/author_evals.html
{% extends 'base.html' %}

{% block content %}


{% for eval in evaluations %}
    <h1>Evaluation Forms Created By {{eval.eval_author}}</h1>   
    <h2>{{ eval.eval_name }}</h2>
    <p>Author: {{ eval.eval_author.name }}</p>
    <p>Date Created: {{ eval.date_created }}</p>

    <h3>Questions and Choices: </h3>

    {% for question in eval.question_set.all %}
        <ul>
            <li>{{ question.question_text }}</li>

            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }}</li>
            {% endfor %}
        </ul>
    {% endfor %}

{% endfor %}

{% endblock content %}

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}

    <div class = "content-section">
        
        <form method="POST">
        {% csrf_token %} 
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">
                    Log In
                </legend>
                {{ form|crispy}}
            </fieldset>

            <div class = "form-group">
                <button class = "btn btn-outline-info" type = "submit">
                    Log In
                </button>
            </div>
        </form>

        <div class = "border-top mt-3">
            <small class = "text-muted"> 
                Need An Account? <a class = "ml-2" href="{% url 'register' %}"> Sign Up Now </a>
            </small>
        </div>
    </div>
    
{% endblock content%}

users/templates/users/logout.html
{% extends "base.html" %}
{% block content %}

    <h2> You have been logged out </h2>

    <div class = "border-top pt-3">
        <small class = "text-muted"> 
            <a href="{% url 'login' %}"> Log In Again </a>
        </small>
    </div>

    
{% endblock content%}

users/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
    <h1>{{user.username}}</h1>
{% endblock content%}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}

    <div class = "content-section">
        
        <form method="POST">
        {% csrf_token %} 
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">
                    Join Today
                </legend>
                {{ form|crispy}}
            </fieldset>

            <div class = "form-group">
                <button class = "btn btn-outline-info" type = "submit">
                    Sign up
                </button>
            </div>
        </form>

        <div class = "border-top pt-3">
            <small class = "text-muted"> 
                Already Have An Account? <a class = "ml-2" href="{% url 'login' %}"> Sign In </a>
            </small>
        </div>
    </div>
    
{% endblock content%}